web/webapp/blueprints/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email


class CreateAccountForm(FlaskForm):
    username = StringField('Username', id='username', validators=[DataRequired()])
    email = StringField('Email', id='email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', id='password', validators=[DataRequired()])

web/webapp/__init__.py
from glob import glob
from flask import Flask
from flask_jwt_extended import JWTManager
from importlib import import_module
from flask_login import LoginManager

login_manager = LoginManager()


def register_blueprints(app):
    for module_name in glob("webapp/blueprints/*/"):
        module = import_module(module_name.replace('/', '.') + 'routes')
        app.register_blueprint(module.blueprint)


def register_extensions(app):
    login_manager.init_app(app)
    login_manager.session_protection = "strong"
    JWTManager(app)


def create_app():
    app = Flask(__name__)
    app.config.from_object('webapp.config.Config')

    register_blueprints(app)
    register_extensions(app)

    with app.app_context():
        # Imports
        from . import routes

        return app

web/webapp/blueprints/cat/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'cat_blueprint',
    __name__,
    url_prefix='/cat',
    template_folder='templates'
)

web/webapp/blueprints/cat/routes.py
import requests
from flask import render_template
from ...blueprints.cat import blueprint


@blueprint.route('/')
def cat():
    cat = requests.get('http://api:8080/api/v1/cats')

    return render_template('cats.html', cat=cat.json(), api_headers=cat.headers)

web/webapp/blueprints/home/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates'
)

web/webapp/blueprints/home/routes.py
from flask import render_template
from ...blueprints.home import blueprint


@blueprint.route('/')
def home():
    return render_template('index.html')

web/webapp/blueprints/joke/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'joke_blueprint',
    __name__,
    url_prefix='/joke',
    template_folder='templates'
)

web/webapp/blueprints/joke/routes.py
import requests
from flask import render_template
from ...blueprints.joke import blueprint


@blueprint.route('/')
def joke():
    p = requests.get('http://api:8080/api/v1/jokes/')
    return render_template('joke.html', joke=p.json()['joke'], api_headers=p.headers)

web/webapp/blueprints/prime/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'prime_blueprint',
    __name__,
    url_prefix='/prime',
    template_folder='templates'
)

web/webapp/blueprints/prime/routes.py
import requests
from flask import render_template
from ...blueprints.prime import blueprint


@blueprint.route('/')
@blueprint.route('/?lower=<int:lower>&upper=<int:upper>')
def primes(lower=0, upper=10000):
    try:
        p = requests.get('http://api:8080/api/v1/primes/?lower={}&upper={}'.format(lower, upper))
        print(p)
        if p.status_code != 200:
            return render_template('primes.html', error=p.json()['detail'], api_headers=p.headers)
        return render_template('primes.html', primes=p.json(), api_headers=p.headers)
    except Exception as e:
        return "Some very good exception handling!" + str(e)


@blueprint.route('/v2')
def v2():
    return render_template('primesv2.html')

web/webapp/blueprints/user/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'user_blueprint',
    __name__,
    url_prefix='/user',
    template_folder='templates'
)

web/webapp/blueprints/user/routes.py
import requests
from flask import render_template, request, redirect, url_for, session
from flask_login import login_required, current_user, logout_user
from ...blueprints.user import blueprint
from ...blueprints.user.forms import CreateAccountForm


# Users overview
@blueprint.route('/')
@login_required
def users():
    try:
        data = requests.get('http://api:8080/api/v1/users', headers={'Authorization': f"Bearer {session['token']}"})
        return render_template('users.html', users=data.json(), api_headers=data.headers)
    except Exception as e:
        return "Some very good exception handling!" + str(e)


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home_blueprint.home'))

    form = CreateAccountForm(request.form)

    if request.method == 'POST':
        try:
            if not form.validate_on_submit():
                return render_template('register.html', form=form)

            data = requests.post('http://api:8080/api/v1/users/create',
                                 json={'username': form.username.data, 'password': form.password.data,
                                       'email': form.email.data})

            if data.status_code == 400:
                return render_template('register.html', error=data.json()['detail'],
                                       api_headers=data.headers, form=form)

            # HTTP Code 201 = "Created"
            if data.status_code != 201:
                return render_template('register.html',
                                       error='Something went wrong! (error code ' + str(data.status_code) + ' )',
                                       api_headers=data.headers, form=form)

            return redirect(url_for('auth_blueprint.login'))
        except Exception as e:
            print(e)
            return "Some very good exception handling!" + str(e)

    return render_template('register.html', form=form)


@blueprint.route('/delete')
@login_required
def delete_users():
    try:
        num_deleted = requests.delete('http://api:8080/api/v1/users/delete',
                                      headers={'Authorization': f"Bearer {session['token']}"}).json()
        logout_user()
        return render_template('users.html', message='All users (' + str(num_deleted) + ') are deleted.')
    except Exception as e:
        return "Some very good exception handling!" + str(e)

web/webapp/blueprints/util.py
from urllib.parse import urlparse, urljoin

from flask import request


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and ref_url.netloc == test_url.netloc

web/webapp/routes.py
import time
import socket
from datetime import datetime

from flask import g, redirect, url_for, request
from flask import current_app as app

from . import login_manager


@app.before_request
def before_request():
    g.request_start_time = time.time()
    g.request_time = lambda: "%.5fs" % (time.time() - g.request_start_time)


@app.context_processor
def inject_hostname():
    return dict(hostname=socket.gethostname())


@app.context_processor
def inject_now():
    return {'now': datetime.utcnow()}


@login_manager.unauthorized_handler
def unauthorized_handler():
    print("======> " + request.full_path)
    return redirect(url_for('auth_blueprint.login', next=request.full_path))

web/webapp/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>Not-so-basic webapp</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Favicons -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <!-- Custom styles for this template -->
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='github-ribbon.css') }}"> -->


</head>
<body>

<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <a class="h5 my-0 me-md-auto fw-normal text-decoration-none text-dark" href="/">Not-so-basic webapp</a>
    <nav class="my-2 my-md-0 me-md-3">
        <a class="p-2 text-dark" href="{{ url_for('user_blueprint.users') }}">Users</a>
        <a class="p-2 text-dark" href="{{ url_for('prime_blueprint.primes') }}">Primes</a>
        <a class="p-2 text-dark" href="{{ url_for('prime_blueprint.v2') }}">Primes V2</a>
        <a class="p-2 text-dark" href="{{ url_for('cat_blueprint.cat') }}">Cat</a>
        <a class="p-2 text-dark" href="{{ url_for('joke_blueprint.joke') }}">Joke</a>
        {% if not current_user.is_authenticated %}
            <a class="p-2 text-dark" href="{{ url_for('auth_blueprint.login') }}">Log in</a>
        {% endif %}
        <!-- <a href="https://github.com/Eslih/basic-webapp" class="ribbon">Fork me on GitHub</a> -->
    </nav>
    {% if current_user.is_authenticated %}
        <a class="btn btn-outline-danger" href="{{ url_for('auth_blueprint.logout') }}">Log out</a>
    {% else %}
        <a class="btn btn-outline-primary" href="{{ url_for('user_blueprint.register') }}">Sign up</a>
    {% endif %}
</header>

<main class="container">
    <div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        {% block content %}{% endblock %}
    </div>


    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                <a href="https://github.com/Eslih/basic-webapp" class="btn btn-outline-secondary btn-sm">
                    <img class="mb-2" src="{{ url_for('static', filename='GitHub-Mark-32px.png') }}" alt="GitHub Mark"
                         width="16px" height="16px">
                    Fork / Star me on GitHub
                </a>
                <small class="d-block mb-3 text-muted"><a href="mailto:esli.heyvaert@howest.be" class="link-secondary">Esli
                    Heyvaert</a> &copy
                    2020 - {{ now.year }}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Technology</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="link-secondary" href="https://www.docker.com/">Docker</a></li>
                    <li><a class="link-secondary" href="https://docs.docker.com/compose/">Docker Compose</a></li>
                    <li><a class="link-secondary" href="https://flask.palletsprojects.com/">Flask</a></li>
                    <li><a class="link-secondary" href="https://fastapi.tiangolo.com/">FastAPI</a></li>
                    <li><a class="link-secondary" href="https://www.nginx.com/">Nginx</a></li>
                    <li><a class="link-secondary" href="https://www.postgresql.org/">PostgreSQL</a></li>
                    <li><a class="link-secondary" href="https://getbootstrap.com/">Bootstrap</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>About</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="link-secondary" href="#" id="api-docs">API Docs</a></li>
                    <li><a class="link-secondary" href="https://github.com/Eslih/basic-webapp">GitHub Source</a></li>
                    <li><a class="link-secondary" href="https://hub.docker.com/u/eslih">Docker Hub</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Stats</h5>
                <ul class="list-unstyled text-small" id="stats">
                    <li>Hostname: {{ hostname }}</li>
                    <li> Frontend Request time: {{ g.request_time() }}</li>
                    {% if api_headers %}
                        <li>API Hostname: {{ api_headers['x-api-hostname'] }}</li>
                        <li>API Processing Time: {{ api_headers['x-process-time'] }}</li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </footer>
</main>
</body>
<script>
    document.getElementById("api-docs").href = window.location.protocol + '//' + window.location.host + ':8080/docs'
</script>
</html>

web/webapp/templates/cats.html
{% extends "base.html" %}
{% block content %}
    <h1 class="display-4">Cats</h1>
    <p class="lead">Look! A cat!</p>
    <h2 class="display-6">{{ cat.name.capitalize() }}</h2>
    <img src="{{ cat.url }}" class="img-fluid" alt="{{ cat.name }}">
{% endblock %}

web/webapp/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="alert alert-success" role="alert">
        <strong>New!</strong> Check-out this cool <a href="{{ url_for('prime_blueprint.v2') }}">prime generator</a>!
    </div>
    {% if current_user.is_authenticated %}
        <h1 class="jumbotron-heading">Index - Logged in!</h1>
        <p class="lead text-muted">Some inspiring text. Give it another <a href="{{ url_for('auth_blueprint.logout') }}">try</a>?</p>
    {% else %}
        <h1 class="display-4">Index</h1>
        <p class="lead">Some inspiring text.</p>
    {% endif %}
{% endblock %}

web/webapp/templates/joke.html
{% extends "base.html" %}
{% block content %}
    <h1 class="display-4">Joke</h1>
    <p class="lead">Whahaha! A joke!</p>

    <blockquote class="blockquote">
        <p class="mb-0">{{ joke }}</p>
    </blockquote>

{% endblock %}

web/webapp/templates/login.html
{% extends "base.html" %}
{% block content %}
    {% if current_user.is_authenticated %}
        <h1 class="display-4">Nothing to do here...</h1>
        <p class="lead">Seems like you're already logged in!</p>
    {% else %}
        <h1 class="display-4">Login</h1>
        <p class="lead">Ready. Set. Awesomeness!</p>

        {% if data %}
            <div class="alert alert-danger" role="alert">
                <p>
                    <strong>You must be retarded!</strong> No user with username <strong>{{ data.username }}</strong>
                    and password <strong>{{ data.password }}</strong>!

                    {{ data.error }}
                </p>
            </div>
            <a href="{{ url_for('auth_blueprint.login') }}" class="btn btn-warning">Try again!</a>
            <a href="{{ url_for('user_blueprint.register') }}" class="btn btn-success">Register!</a>
        {% endif %}
        {% if form.errors.items() %}
            <div class="alert alert-danger" role="alert">
                {% for field, errors in form.errors.items() %}
                    <p><strong>{{ form[field].label }}:</strong> {{ ', '.join(errors) }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <form role="form" action="" method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.email.label(class="form-label") }}
                {{ form.email(placeholder="Enter email", class="form-control") }}
            </div>
            <div class="mb-3">
                {{ form.password.label(class="form-label") }}
                {{ form.password(placeholder="Enter password", class="form-control", type="password") }}
            </div>
            <button type="submit" class="btn btn-primary">Login!</button>
        </form>
    {% endif %}
{% endblock %}

web/webapp/templates/primes.html
{% extends "base.html" %}
{% block content %}
    <h1 class="display-4">Prime numbers!</h1>
    <p class="lead">Oh dear! Here we go again... You know? This request is quite heavy for the API!</p>
    <p>
        Try it yourself! Example: <a href="{{ url_for('prime_blueprint.primes') }}?lower=100&upper=1000">/?lower=100&upper=1000</a>
    </p>
    {% if error %}
        <div class="alert alert-danger" role="alert">
            <strong>Woops!</strong> {{ error }}
        </div>
    {% else %}
        <p>
            {% for prime in primes %}
                <span class="badge bg-light text-dark">{{ prime }}</span>
            {% endfor %}
        </p>
    {% endif %}
{% endblock %}

web/webapp/templates/primesv2.html
{% extends "base.html" %}
{% block content %}
    <h1 class="display-4" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">Prime numbers!</h1>
    <p class="lead">Oh dear! Here we go again... You know? This request is quite heavy for the API!</p>
    <p>
        Although this version looks quite similar to <a href="{{ url_for('prime_blueprint.primes') }}">primes v1</a>, it
        works differently! V2 is using (vanilla) JavaScript to fetch the prime numbers directly from the API. This way
        the front-end is rendered immediately!
    </p>
    <p class="muted">
        Oh, by the way... . The JavaScript code still needs some <strong>&hearts;</strong>. Feel free to fork
        <a href="https://github.com/Eslih/basic-webapp">this app</a> and
        <a href="https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request">
            create a pull request</a>!
    </p>
    <p>
        Try it yourself! Example: <a href="{{ url_for('prime_blueprint.v2') }}?lower=100&upper=1000">/?lower=100&upper=1000</a>
    </p>

    <p>
        {% for prime in primes %}
            <span class="badge bg-light text-dark">{{ prime }}</span>
        {% endfor %}
    </p>
    <div id="primes">
        <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
    <script>
        {# I know... this should be refactored somewhat :D #}
        let getParams = function (url) {
            let params = {};
            let parser = document.createElement('a');
            parser.href = url;
            let query = parser.search.substring(1);
            let vars = query.split('&');
            for (let i = 0; i < vars.length; i++) {
                let pair = vars[i].split('=');
                params[pair[0]] = decodeURIComponent(pair[1]);
            }
            return params;
        };
        let params = getParams(window.location.href)
        let lower = 0
        let upper = 10000
        if (params) {
            if (params.lower) {
                lower = params.lower
            }
            if (params.upper) {
                upper = params.upper
            }
        }
        fetch(window.location.protocol + '//' + window.location.host + ':8080/api/v1/primes/?lower=' + lower + '&upper=' + upper).then(function (response) {
            // The API call was successful!
            if (response.ok) {
                document.querySelector('#stats').innerHTML += '' +
                    '<li>API Hostname: ' + response.headers.get('x-api-hostname') + '</li>' +
                    '<li>API Processing Time: ' + response.headers.get('x-process-time') + '</li>'
                return response.json();
            } else {
                return Promise.reject(response);
            }
        }).then(function (data) {
            // This is the JSON from our response
            let elem = document.querySelector('#primes');

            // Set HTML content
            let i, primes = '';
            for (i = 0; i < data.length; i++) {
                primes += '<span class="badge bg-light text-dark">' + data[i] + '</span>';
            }
            elem.innerHTML = primes;
        }).catch(function (err) {
            // There was an error

            document.querySelector('#primes').innerHTML = '' +
                '<div class="alert alert-danger" role="alert">' +
                '<strong>Woops!</strong> Something went wrong!' +
                '</div>'
        });
    </script>
{% endblock %}

web/webapp/templates/register.html
{% extends "base.html" %}
{% block content %}
    {% if current_user.is_authenticated %}
        <h1 class="display-4">Nothing to do here...</h1>
        <p class="lead">Seems like you're already logged in!</p>
    {% else %}
        <h1 class="display-4">Register</h1>
        <p class="lead">You won't regret, coolest app ever!</p>
        {% if error or form.errors.items() %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
                {% for field, errors in form.errors.items() %}
                    <p><strong>{{ form[field].label }}:</strong> {{ ', '.join(errors) }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <form role="form" action="" method="POST">
            {{ form.hidden_tag() }}
            <div class="mb-3">
                {{ form.username.label(class="form-label") }}
                {{ form.username(placeholder="Enter username", class="form-control") }}
            </div>
            <div class="mb-3">
                {{ form.email.label(class="form-label") }}
                {{ form.email(placeholder="Enter email", class="form-control") }}
            </div>
            <div class="mb-3">
                {{ form.password.label(class="form-label") }}
                {{ form.password(placeholder="Enter password", class="form-control", type="password") }}
            </div>
            <button type="submit" class="btn btn-success">Register!</button>
        </form>
    {% endif %}
{% endblock %}

web/webapp/templates/users.html
{% extends "base.html" %}
{% block content %}
    <h1 class="jumbotron-heading">Users overview</h1>
    {% if users %}
        <p>
            Look at this beautiful table. It shows all the users their credentials.
        </p>
        <p>
            <a class="btn btn-danger btn-lg" href="{{ url_for('user_blueprint.delete_users') }}" role="button">Delete users</a>
        </p>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Username</th>
                <th scope="col">Email</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <th scope="row">{{ user.id }}</th>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-warning" role="alert">
            {{ message }} <a href="{{ url_for('user_blueprint.register') }}">Register</a>!
        </div>
    {% endif %}
{% endblock %}